"""OpenAI specific implementation."""
from typing import Dict, Any
from .base_llm import BaseLLMAdapter

class OpenAIAdapter(BaseLLMAdapter):
    def generate(self, prompt: str, context: Dict[str, Any]) -> Dict[str, Any]:
        """Calls OpenAI API forcing JSON structured output."""
        return {
            "summary": "Generated by OpenAI",
            "recommendation": "Mocked",
            "warnings": [],
            "citations": [],
            "confidence": "High"
        }
